on:
  push:
    branches:
    - main
    - feat/set-action
    
jobs:
  build:
    name: Build front-end
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v3.6.0
      with:
        node-version-file: ./front/.nvmrc

    - name: Install yarn
      run: npm i -g yarn

    - name: Install dependencies
      run: yarn
      working-directory: ./front

    - name: Build
      run: yarn build
      working-directory: ./front

    - name: Setup pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      working-directory: ./front
      with:
        path: './dist'

    - name: Deploy to GH Pages
      id: deploy
      uses: actions/deploy-pages@v1
